### PR TITLE
Removed Inline and Internal CSS and moved those to assets

### LINKED ISSUE #17: Move Inline Styles to External CSS File
Move all the Inline Styles to an External CSS File.

**Note**- 
* Be careful, nothing should break.
* External CSS File should be created in **assets** folder.

### PR DESCRIPTION
**Pull request by dhanrajchaurasia**
Fixes #17 (All the inline and internal CSS are removed, Two external css files are added in the assets folder and 404 page's CSS is unchanged(some issues are there).

### CODE REVIEW

**Comment by dhanrajchaurasia** [comment]
Sir I have tried to make 404.css which keeps external css of 404 page but sir 404 page was not loading due to Debug=True in .env file so I contacted with Kshitiz Sir so he told that to change it to False to make 404 page work but after making it False any of the external css was not loading that's why I asked him to keep the internal css of 404 to unchanged so he allowed me.

**Comment by ankitsangwan1999** [comment]
> Sir I have tried to make 404.css which keeps external css of 404 page but sir 404 page was not loading due to Debug=True in .env file so I contacted with Kshitiz Sir so he told that to change it to False to make 404 page work but after making it False any of the external css was not loading that's why I asked him to keep the internal css of 404 to unchanged so he allowed me.

Ok. So, just keep Debug=True i.e. for dev mode, and apply the external CSS externally to 404.html as intended. Check if the CSS is working on 404.html not by DEBUG=False but instead by making the 404.html file rendered from any view for e.g. just write `return render(request, '404.html')` in any view like home. Confirm if CSS is loading properly, if it is not working fine then inform me here and we will look into that.

**Comment by dhanrajchaurasia** [comment]
Yes Sir after adding into urls.py and views.py 404.html is working with external CSS but sir then the 404 page will render with just a particular URL (e.g. I used '/Not_Found' to render '404.html'). So sir what to do now?

**Comment by ankitsangwan1999** [comment]
As the external CSS styles are linked properly with 404.html, now just remove the urls/views you created for testing and keep the 404.html page like that only. Now, in production mode whenever a user will visit on any non-existing route they will see this 404.html page( this is an already implemented feature).

**Comment by ankitsangwan1999** [comment]
You can push these changes on this PR.

**Pull request merged**
